import { type Page, type Locator, expect } from '@playwright/test';

/**
 * Shared building blocks for the portal's react-aria forms.
 *
 * Every form in the portal (profile wizard, job wizard, …) is built from the same widgets, and
 * each of them needs more than a plain `fill()`/`click()`: comboboxes open only on real key
 * presses and load their options lazily, descriptions are contenteditable editors, and sliders are
 * visually-hidden range inputs behind a draggable handle. The handling of those widgets lives here
 * so each page object only describes its own fields.
 */
export class ReactAriaPage {
  readonly main: Locator;

  constructor(protected readonly page: Page) {
    this.main = page.locator('main');
  }

  /** Input with id `id` (ids of repeatable records contain dots, so an attribute selector is used). */
  protected byId(id: string): Locator {
    return this.page.locator(`[id="${id}"]`);
  }

  /**
   * Wrapper element of a labelled field: the `<label>` whose text starts with `label` together
   * with the controls rendered next to it. Field ids are generated by react-aria, so controls that
   * carry no id or accessible name of their own (the vacancy stepper, the experience slider) are
   * reached through their label instead of through a class name.
   */
  protected fieldByLabel(label: RegExp): Locator {
    return this.main.locator('label').filter({ hasText: label }).locator('xpath=..');
  }

  /** Fills a text-like input only when it is still empty; existing values are left untouched. */
  async fillIfEmpty(locator: Locator, value: string) {
    // A step can re-render once more shortly after it opens (its data is fetched again), which
    // wipes a value typed in that window. Re-check once the network is quiet and refill if so.
    await expect(async () => {
      if (!(await locator.inputValue()).trim()) {
        await locator.fill(value);
      }
      await this.page.waitForLoadState('networkidle');
      await expect(locator).not.toHaveValue('', { timeout: 1_000 });
    }).toPass({ timeout: 20_000, intervals: [500, 1_000] });
  }

  /**
   * Picks an option in a react-aria combobox. The listbox opens only on real key presses, so the
   * search text is typed; `optionName` selects a specific option, otherwise the first match wins.
   * Multi-select comboboxes keep their popover open after a pick, so it is closed explicitly.
   */
  async pickComboOption(combo: Locator, search: string, optionName?: string | RegExp, { multi = false } = {}) {
    // A string name must match exactly ("Communication" is also part of "Microwave Communication").
    const option = optionName
      ? this.page.getByRole('option', { name: optionName, exact: typeof optionName === 'string' })
      : this.page.getByRole('option').first();
    const normalize = (s: string) => s.replace(/\s+/g, ' ').trim();

    // The list re-renders while the search text filters it, so a click can land on an option that
    // is being replaced and commit nothing (the typed text then looks like a value until the form
    // validates). Repeat the whole pick until the combobox reports the chosen option as its value.
    await expect(async () => {
      await combo.click();
      if (search) {
        await combo.fill('');
        await this.page.keyboard.type(search, { delay: 30 });
      }
      if ((await combo.getAttribute('aria-expanded')) !== 'true') await this.page.keyboard.press('ArrowDown');
      await expect(option).toBeVisible({ timeout: 3_000 });

      const chosen = normalize(await option.innerText());
      await option.click();
      if (!multi) {
        await expect
          .poll(async () => normalize(await combo.inputValue()), { timeout: 3_000 })
          .toBe(chosen);
        // Option lists load lazily; a pick made against a list that is still loading is dropped
        // when the data arrives. Re-check once the network has settled so such a revert retries.
        await this.page.waitForLoadState('networkidle');
        await expect
          .poll(async () => normalize(await combo.inputValue()), { timeout: 2_000 })
          .toBe(chosen);
      }
    }).toPass({ timeout: 45_000, intervals: [500, 1_000, 2_000] });

    // Single-select comboboxes close on their own after a pick, and Escape while they are still
    // open would revert the selection. Multi-select ones stay open, so only those get Escape.
    const listbox = this.page.getByRole('listbox');
    const stillOpen = await listbox.waitFor({ state: 'hidden', timeout: 2_000 }).then(() => false, () => true);
    if (stillOpen) await this.page.keyboard.press('Escape');
    await expect(listbox).toHaveCount(0);
  }

  /** Single-value combobox: picks an option only when nothing is selected yet. */
  async pickComboIfEmpty(combo: Locator, search: string, optionName?: string | RegExp) {
    if (!(await combo.inputValue()).trim()) {
      await this.pickComboOption(combo, search, optionName);
    }
    await expect(combo).not.toHaveValue('');
  }

  /** Multi-select combobox: adds `optionName` as a tag unless that tag is already present. */
  async addTag(combo: Locator, optionName: string) {
    const tag = combo.locator('xpath=ancestor::*[@role="group"][1]').getByText(optionName, { exact: true });
    if (await tag.count()) return;
    await this.pickComboOption(combo, optionName, optionName, { multi: true });
    // Typed search text stays in the input after a multi-select pick; clear it for the next one.
    if (await combo.inputValue()) await combo.fill('');
    await expect(tag).toBeVisible();
  }

  /**
   * Option names a combobox offers right now. The list opens on a key press and loads lazily, so
   * the first option is awaited; placeholders ("Select …", "No results") are dropped. The list is
   * closed again without picking anything, so calling this changes nothing.
   */
  async optionNames(combo: Locator): Promise<string[]> {
    await combo.click();
    if ((await combo.getAttribute('aria-expanded')) !== 'true') await this.page.keyboard.press('ArrowDown');
    const listbox = this.page.getByRole('listbox');
    await expect(listbox).toBeVisible({ timeout: 15_000 });
    await expect(this.page.getByRole('option').first()).toBeVisible({ timeout: 15_000 });

    const names = (await this.page.getByRole('option').allInnerTexts())
      .map((s) => s.replace(/\s+/g, ' ').trim())
      .filter((s) => s && !/^(select|choose|no options|no results)/i.test(s));

    await this.page.keyboard.press('Escape');
    await expect(listbox).toHaveCount(0);
    return [...new Set(names)];
  }

  /** Types into a rich-text editor only when it has no content yet. */
  async fillEditorIfEmpty(editor: Locator, text: string) {
    if (!(await editor.innerText()).trim()) {
      await editor.click();
      await this.page.keyboard.type(text);
    }
    await expect(editor).toContainText(text.slice(0, 40));
  }

  /**
   * Moves a react-aria range slider to `target` with the keyboard (PageUp/PageDown for big steps,
   * arrows for single steps), driven by the value the slider actually reports after each key.
   *
   * How far a Page key jumps depends on the slider's range (5 on the 1–50 experience slider, far
   * more on the 10–900 salary one), so the jump is measured from the first Page key and from then
   * on a Page key is only used while more than one jump is left. Otherwise a slider with a large
   * page step would overshoot the target and jump back and forth around it forever.
   */
  async setSlider(slider: Locator, target: number) {
    const min = Number((await slider.getAttribute('min')) ?? 1);
    const max = Number((await slider.getAttribute('max')) ?? 100);
    const step = Number((await slider.getAttribute('step')) ?? 1);
    expect(target, `slider value must be within ${min}–${max}`).toBeGreaterThanOrEqual(min);
    expect(target, `slider value must be within ${min}–${max}`).toBeLessThanOrEqual(max);
    // A slider only stops on multiples of its step (the project budget moves in 500s), so a
    // target in between could never be reached and is a mistake in the test data.
    expect(
      (target - min) % step,
      `slider value ${target} is not reachable: the slider moves from ${min} in steps of ${step}`,
    ).toBe(0);

    await slider.focus();
    let current = Number(await slider.inputValue());
    let pageStep = 0;
    for (let guard = 0; current !== target && guard < 400; guard++) {
      const diff = target - current;
      const usePage = pageStep === 0 ? Math.abs(diff) >= 10 : Math.abs(diff) > pageStep;
      const key = usePage ? (diff > 0 ? 'PageUp' : 'PageDown') : diff > 0 ? 'ArrowRight' : 'ArrowLeft';
      await slider.press(key);
      const next = Number(await slider.inputValue());
      if (next === current) throw new Error(`Slider did not move on ${key} (stuck at ${current}, target ${target})`);
      if (usePage) pageStep = Math.abs(next - current);
      current = next;
    }
    await expect(slider).toHaveValue(String(target));
  }

  // ---- Two-thumb range sliders ---------------------------------------------------------------

  /** The two visually hidden range inputs of a range slider: [0] is the lower thumb, [1] the upper. */
  rangeInputs(group: Locator): Locator {
    return group.getByRole('slider');
  }

  /** The bar the handles travel along. The value read-outs are also `[data-orientation]` elements. */
  private rangeTrack(group: Locator): Locator {
    return group.locator('[data-orientation="horizontal"]').first();
  }

  private rangeHandles(group: Locator): Locator {
    return group.locator('.cursor-grab');
  }

  /**
   * Sets both ends of a two-thumb react-aria range slider (the job salary, the project budget) by
   * dragging its handles along the bar.
   *
   * Each handle's own min/max move with the other handle — the lower one cannot pass the upper —
   * so the overall bounds are read once before anything moves and the drags are positioned against
   * those. The upper handle goes first: raising it can never collide with the lower one.
   */
  async setRangeSlider(group: Locator, lower: number, upper: number) {
    expect(lower, 'the lower end of the range must stay below the upper end').toBeLessThan(upper);
    const inputs = this.rangeInputs(group);
    await expect(inputs, 'a range slider should offer two thumbs').toHaveCount(2);
    await expect(this.rangeHandles(group), 'a range slider should offer two handles').toHaveCount(2);

    const min = Number(await inputs.nth(0).getAttribute('min'));
    const max = Number(await inputs.nth(1).getAttribute('max'));
    expect(lower, `the range must be within the slider's ${min}–${max}`).toBeGreaterThanOrEqual(min);
    expect(upper, `the range must be within the slider's ${min}–${max}`).toBeLessThanOrEqual(max);

    await this.dragRangeHandle(group, 1, upper, min, max);
    await this.dragRangeHandle(group, 0, lower, min, max);

    await expect(inputs.nth(0)).toHaveValue(String(lower));
    await expect(inputs.nth(1)).toHaveValue(String(upper));
    expect(
      Number(await inputs.nth(0).inputValue()),
      'the lower end of the range must stay below the upper end',
    ).toBeLessThan(Number(await inputs.nth(1).inputValue()));
  }

  /**
   * Drags one handle of a range slider to `target`, then finishes the move exactly with the
   * keyboard. The drag has to do the work: it must land within a few pixels' worth of value, and
   * where it started further away than that it must also have closed the gap, so a drag that goes
   * nowhere fails here instead of being covered up by the keyboard.
   */
  private async dragRangeHandle(group: Locator, index: 0 | 1, target: number, min: number, max: number) {
    const handle = this.rangeHandles(group).nth(index);
    const slider = this.rangeInputs(group).nth(index);
    await handle.scrollIntoViewIfNeeded();

    const track = await this.rangeTrack(group).boundingBox();
    const box = await handle.boundingBox();
    expect(track, 'the slider bar should be measurable').not.toBeNull();
    expect(box, 'the slider handle should be measurable').not.toBeNull();

    const before = Number(await slider.inputValue());
    const step = Number((await slider.getAttribute('step')) ?? 1);
    const y = box!.y + box!.height / 2;
    await this.page.mouse.move(box!.x + box!.width / 2, y);
    await this.page.mouse.down();
    await this.page.mouse.move(track!.x + (track!.width * (target - min)) / (max - min), y, { steps: 15 });
    await this.page.mouse.up();

    // Five pixels' worth of value, so the check scales with the slider's own range and width.
    const tolerance = Math.max(2 * step, Math.ceil(((max - min) * 5) / track!.width));
    await expect
      .poll(async () => Math.abs(Number(await slider.inputValue()) - target), {
        message: `dragging handle ${index} should land within ${tolerance} of ${target}`,
        timeout: 10_000,
      })
      .toBeLessThanOrEqual(tolerance);
    if (Math.abs(before - target) > tolerance) {
      expect(
        Math.abs(Number(await slider.inputValue()) - target),
        `dragging handle ${index} should have moved it towards ${target} (it started at ${before})`,
      ).toBeLessThan(Math.abs(before - target));
    }

    await this.setSlider(slider, target);
  }
}

export function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
